jobs:
  include:
    - stage: test
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
      node_js:
        - 13.12.0
    - stage: doc
      node_js: lts/*
      script:
        - npm run lint
        - npm run docs
      cleanup: 'false'
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        cleanup: 'false'
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
